// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClUVsIVY1ZDeAqq1l17Oq_S2Ft06KsJdM',
    appId: '1:410996358427:web:6219389c9b9a1bfd95e7be',
    messagingSenderId: '410996358427',
    projectId: 'kafekotakita-community',
    authDomain: 'kafekotakita-community.firebaseapp.com',
    storageBucket: 'kafekotakita-community.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRtcekkoSZBBhUETvzMXmkvxVPmM1whxE',
    appId: '1:410996358427:android:c8d5843b3d91ed5795e7be',
    messagingSenderId: '410996358427',
    projectId: 'kafekotakita-community',
    storageBucket: 'kafekotakita-community.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUlBNqdQbnAO8UuYf2tfh6bse_ae5LFsU',
    appId: '1:410996358427:ios:b381fba9d958e11d95e7be',
    messagingSenderId: '410996358427',
    projectId: 'kafekotakita-community',
    storageBucket: 'kafekotakita-community.firebasestorage.app',
    iosBundleId: 'com.example.tugasFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUlBNqdQbnAO8UuYf2tfh6bse_ae5LFsU',
    appId: '1:410996358427:ios:b381fba9d958e11d95e7be',
    messagingSenderId: '410996358427',
    projectId: 'kafekotakita-community',
    storageBucket: 'kafekotakita-community.firebasestorage.app',
    iosBundleId: 'com.example.tugasFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClUVsIVY1ZDeAqq1l17Oq_S2Ft06KsJdM',
    appId: '1:410996358427:web:e8407e630c62cfc395e7be',
    messagingSenderId: '410996358427',
    projectId: 'kafekotakita-community',
    authDomain: 'kafekotakita-community.firebaseapp.com',
    storageBucket: 'kafekotakita-community.firebasestorage.app',
  );
}
